spring:
  h2:
    console:
      enabled: true

  jackson:
    serialization:
      write-dates-as-timestamps: false

security:
  user:
    password: javacro

info:
  build:
    name: ${name}
    version: ${version}
